### ISSUE TITLE
wrap-forwarded-remote-addr ELB compatibility

### ISSUE THREAD

**Issue by g-k** [ring-clojure/ring-headers#7]
Can you elaborate on the commit message for https://github.com/ring-clojure/ring-headers/commit/2b3ea70584ae61c1414953180938d2b14153850d?

> Middleware function incorrectly used the first rather than last value present in the X-Forwarded-For header. This could result in attackers being able to spoof the :remote-addr key if this middleware was used. Reported by Daniel Compton <desk@danielcompton.net>.

Shouldn't a load balancer should either set the X-Forwarded-For header or not forward it at all?

Since that commit breaks compatibility with [ELB](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html#x-forwarded-for) could we make using the first or last IP configurable?

**Comment by weavejester** [comment]
Does ELB proxy the request through more than one server then? One option is to allow a setting where the `:remote-addr` is set `n` before the last.

We don't want to make it use the first IP, because the first IP can be set by the client to whatever they want, making it unreliable.

**Comment by g-k** [comment]
> Does ELB proxy the request through more than one server?

Not in general, but requests that go client -> ELB -> API gateway/facade -> ELB -> microservice 
with every layer conforming to the AWS X-Forwarded-For format have multiple IPs.

I understand that clients can send packets with a spoofed origin IP, but I'm still not clear on why the last IP would be more or less reliable (maybe it depends on the LB?).

Regardless, an option to pull the nth-to-last IP would be great since the number of proxies should be constant.  I can make a PR for that change (I figure it'd return `nil` when there aren't enough IPs in the header).

**Comment by weavejester** [comment]
Proxies always add IP addresses onto the end of the `X-Forwarded-For` header. So if you have one proxy then you know that the last address in `X-Forwarded-For` was set by a service under your control. If you have two proxies, then the last two addresses were set by services under your control, and so forth.

This means that taking the nth-from-last address, where n is the number of proxies, is reliable as it was set by a service under your control. Taking the first address is unreliable, because it can be set by a service out of your control.

I'd accept an additional argument on the middleware, `n`, defaulting to 0, and representing the number of positions from the last address. So 0 is the last address, 1 is the penultimate address, and so on.

**Comment by g-k** [comment]
OK for some reason I thought `wrap-forwarded-remote-addr` was supposed to set `remote-addr` to the client IP and not the last proxy.

https://github.com/ring-clojure/ring/wiki/Concepts#requests

**Comment by weavejester** [comment]
It sets `:remote-addr` to the IP address that sent the request to the last proxy. If there is only one proxy, then the IP address is equivalent to the client address. The wiki is worded a little incorrectly, so I'll fix it.

**Comment by g-k** [comment]
No problem, thanks for clearing that up for me.

**Comment by seancorfield** [comment]
I just ran into this problem. We have F5 Big-IP and the way this middleware works, it always returns the IP of the load balancer, not the client IP (which is what we wanted). Now I understand what the intent is, I'll switch to using a different middleware.

**Comment by glenjamin** [comment]
I jiust ran into this too, an arg for "trust N proxies" would be handy 👍
